services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: 0.0.0.0
    volumes:
      # Montar solo carpetas específicas si necesitas desarrollo en caliente
      # Si no necesitas hot-reloading, elimina esta sección
      - ./public:/app/public
      - ./static:/app/.next/static
    restart: unless-stopped
